version: '2'
services:
    griphook-app:
        image: griphook
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://griphook-mysql:3306/griphook?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    griphook-mysql:
        extends:
            file: mysql.yml
            service: griphook-mysql
